version: '3.3'

services:
  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - "8096:8096"
    volumes:
      - jellyfin_config:/config
      - /pfad/zu/deinen/filmen:/media
    restart: unless-stopped

volumes:
  jellyfin_config:
