version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"      # DNS TCP
      - "53:53/udp"      # DNS UDP
      - "80:80/tcp"      # Web Interface
    environment:
      TZ: "Europe/Berlin"               # Zeitzone anpassen
      WEBPASSWORD: "deinPasswort"       # Web Interface Passwort
      DNS1: 1.1.1.1                    # Upstream DNS 1
      DNS2: 1.0.0.1                    # Upstream DNS 2
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN                       # Für Netzwerkrechte
    dns:
      - 127.0.0.1
      - 1.1.1.1
