---
- name: Update and upgrade packages on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Update apt cache and upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
